version: '3'
services:

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=counter
    volumes: 
      - data:/var/lib/postgresql/data

  node-app-dev:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: develop.Dockerfile
    restart: on-failure
    environment:
      DB_USER: user
      DB_HOST: postgres
      DB_DATABASE: counter
      DB_PASSWORD: password
      DB_PORT: 5432
      NODE_ENV: development
    volumes:
      - .:/app
    ports:
      - "3000:3000" 


  # node-app-prod:
  #   depends_on:
  #     - postgres
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: on-failure
  #   environment:
  #     DB_USER: user
  #     DB_HOST: postgres
  #     DB_DATABASE: counter
  #     DB_PASSWORD: password
  #     DB_PORT: 5432
  #     NODE_ENV: production
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "3000:3000" 

volumes:
  data: 
